inherit_gem:
  vinted-rubocop:
    - .rubocop.yml

Naming/AccessorMethodName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: true

AllCops:
  SuggestExtensions: false
