inherit_gem:
  rubocop-vinted:
    - .rubocop.default.yml

Naming/AccessorMethodName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: true

AllCops:
  SuggestExtensions: false
